#!/bin/bash

args=
for y in "$@"; do
  if [ "$y" == "$1" ]; then continue; fi
  args="$args $y"
done

file=$(basename $1 .java)
dir=$(dirname $1)

javac -encoding UTF-8 "$dir/$file.java" && java -Dfile.encoding=UTF-8 "$dir/$file" $args
